(require 'dired)
(use-package dired-subtree
  :bind (
    :map dired-mode-map
    ("TAB" . dired-subtree-toggle)))
(use-package multiple-cursors
  :bind (
    ("C-S-c C-S-c" . mc/edit-lines)
    ("C->" . mc/mark-next-like-this)
    ("C-<" . mc/mark-previous-like-this)
    ("C-c C-<" . mc/mark-all-like-this)))
(menu-bar-mode -1)
(tool-bar-mode -1)
(scroll-bar-mode -1)
(global-display-line-numbers-mode 1)
(define-key dired-mode-map (kbd "e") 'dired-create-empty-file)
(setq auto-save-default nil)
(setq make-backup-files nil)
(setq create-lockfiles nil)
(setq dired-dwim-target t)
(setq inhibit-startup-screen t)
(setq initial-buffer-choice t)
(setq initial-scratch-message "")
(setq ring-bell-function 'ignore)
(setq custom-file (expand-file-name "custom.el" user-emacs-directory))
(setq-default indent-tabs-mode nil)
(setq-default tab-width 4)
(setq-default truncate-lines t)
(add-to-list 'default-frame-alist '(font . "monospace-12"))
(add-to-list 'display-buffer-alist '("*Async Shell Command*" display-buffer-no-window (nil)))
(load-theme 'nord t)
(load custom-file 'noerror)
(load (expand-file-name "indent.el" user-emacs-directory))
(load (expand-file-name "autocomplete.el" user-emacs-directory))
(load (expand-file-name "email.el" user-emacs-directory) 'noerror)
(load (expand-file-name "cp-mode.el" user-emacs-directory) 'noerror)

